# Generated by Django 5.0 on 2023-12-18 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_address_zip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='inventrory',
            new_name='inventory',
        ),
    ]
